bosh.js: Copy new attributes to ensure that 'rid' is NOT cleared.
Caused the following exception:
TypeError: Cannot call method 'toString' of undefined
    at map (/root/node-xmpp-bosh-read-only/src/dutil.js:115:17)
    at Object.sprintf (/root/node-xmpp-bosh-read-only/src/dutil.js:124:13)
    at Array.0 (/root/node-xmpp-bosh-read-only/src/bosh.js:573:18)
    at Object.log_it (/root/node-xmpp-bosh-read-only/src/dutil.js:274:17)
    at get_response_object (/root/node-xmpp-bosh-read-only/src/bosh.js:570:10)
    at send_pending_responses (/root/node-xmpp-bosh-read-only/src/bosh.js:945:13)
    at _handle_incoming_request (/root/node-xmpp-bosh-read-only/src/bosh.js:1280:4)
    at _on_data_end (/root/node-xmpp-bosh-read-only/src/bosh.js:1386:3)
    at /root/node-xmpp-bosh-read-only/src/bosh.js:1435:5
    at /root/node-xmpp-bosh-read-only/src/dutil.js:147:16